theme = "onedark"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "separator", "file-name"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "|"

[editor.file-picker]
hidden = false

[keys.normal]
J = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]

K = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
